build:
    shopwareVersionConstraint: ~6.6.0
    zip:
        composer:
            enabled: false
        assets:
            enabled: true
            enable_es_build_for_admin: true
            enable_es_build_for_storefront: true
