version: "3"

services:
  shopware:
    image: dockware/dev:6.6.0.0
    ports:
      - "8080:80"
      - "8443:443"
      - "3310:3306"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
        - ".:/var/www/html/custom/plugins/KskHeptacomAdminOpenAuth"
        # exclude by using anonymous volumes
        - "/var/www/html/custom/plugins/KskHeptacomAdminOpenAuth/.git/"
        - "/var/www/html/custom/plugins/KskHeptacomAdminOpenAuth/vendor/"
        - "/var/www/html/custom/plugins/KskHeptacomAdminOpenAuth/src/Resources/app/administration/node_modules/"
    environment:
      - XDEBUG_ENABLED=1
