services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appSecret: '%env(APP_SECRET)%'
            Doctrine\DBAL\Connection $connection: '@Doctrine\DBAL\Connection'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepository $clientsRepository: '@heptacom_admin_open_auth_client.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepository $loginsRepository: '@heptacom_admin_open_auth_login.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepository $userEmailsRepository: '@heptacom_admin_open_auth_user_email.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepository $userKeysRepository: '@heptacom_admin_open_auth_user_key.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepository $userTokensRepository: '@heptacom_admin_open_auth_user_token.repository'
            Shopware\Core\Framework\DataAbstractionLayer\EntityRepository $scheduledTaskRepository: '@scheduled_task.repository'
            Psr\Http\Client\ClientInterface $oidcHttpClient: '@heptacom.admin_open_auth.oidc.http_client'
            Psr\Http\Client\ClientInterface $samlHttpClient: '@heptacom.admin_open_auth.saml.http_client'
            Psr\Log\LoggerInterface $logger: '@logger'

    _instanceof:
        Heptacom\AdminOpenAuth\Contract\ClientProvider\ClientProviderContract:
            tags:
                - 'heptacom_open_auth.client_provider'
        Heptacom\AdminOpenAuth\Contract\RuleContract:
            tags:
                - { name: 'shopware.rule.definition' }
        Shopware\Core\Framework\DataAbstractionLayer\EntityExtension:
            tags:
                - 'shopware.entity.extension'
        Shopware\Core\Framework\MessageQueue\ScheduledTask\ScheduledTask:
            tags:
                - 'shopware.scheduled.task'
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags:
                - 'kernel.event_subscriber'
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags:
                - 'messenger.message_handler'
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            public: true
            calls:
                - setContainer: [ '@service_container' ]

    Heptacom\AdminOpenAuth\:
        resource: '../../*'
        exclude:
            - '../../Database/*Collection.php'
            - '../../Database/*Entity.php'
            - '../../Exception/*'
            - '../../Migration/*'
            - '../../Resources/*'

    heptacom.admin_open_auth.oidc.http_client:
        class: 'GuzzleHttp\Client'
        arguments:
            - protocols: [https]
              verify: true
              timeout: 15
              headers:
                  Accept: application/json

    heptacom.admin_open_auth.saml.http_client:
        class: 'GuzzleHttp\Client'
        arguments:
            - protocols: [https]
              verify: true
              timeout: 15
              headers:
                  Accept: text/xml,application/xml

    Heptacom\AdminOpenAuth\Database\ClientDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_client' }
    Heptacom\AdminOpenAuth\Database\Aggregate\ClientAclRoleDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_client_role' }
    Heptacom\AdminOpenAuth\Database\LoginDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_login' }
    Heptacom\AdminOpenAuth\Database\UserEmailDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_email' }
    Heptacom\AdminOpenAuth\Database\UserKeyDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_key' }
    Heptacom\AdminOpenAuth\Database\UserTokenDefinition:
        tags:
            - { name: shopware.entity.definition , entity: 'heptacom_admin_open_auth_user_token' }

    Heptacom\AdminOpenAuth\Component\OpenAuth\AuthorizationServer:
        decorates: shopware.api.authorization_server
        parent: shopware.api.authorization_server
        calls:
            - setDecorated: [ '@Heptacom\AdminOpenAuth\Component\OpenAuth\AuthorizationServer.inner' ]
            - setSystemConfigService: [ '@Shopware\Core\System\SystemConfig\SystemConfigService' ]

    Heptacom\AdminOpenAuth\Contract\Client\ClientFactoryContract:
        arguments:
            - '@Heptacom\AdminOpenAuth\Contract\ClientProvider\ClientProviderRepositoryContract'

    Heptacom\AdminOpenAuth\Contract\ClientProvider\ClientProviderRepositoryContract:
        arguments:
            - !tagged_iterator heptacom_open_auth.client_provider

    Heptacom\AdminOpenAuth\Http\Route\Support\RedirectReceiveRoute:
        arguments:
            - '@Heptacom\AdminOpenAuth\Contract\Client\ClientFactoryContract'
            - '@event_dispatcher'

    Heptacom\AdminOpenAuth\Service\OpenAuth\OneTimeTokenClientRepository:
        decorates: Shopware\Core\Framework\Api\OAuth\ClientRepository
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\OpenAuth\OneTimeTokenClientRepository.inner'

    Heptacom\AdminOpenAuth\Service\Provider\CidaasClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\CidaasClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\GoogleCloudClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\GoogleCloudClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\JiraClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\JiraClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\JumpCloudClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\JumpCloudClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\KeycloakClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\KeycloakClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\MicrosoftAzureOidcClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\MicrosoftAzureOidcClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\OktaClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\OktaClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\OneLoginClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\OneLoginClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\OpenIdConnectClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\OpenIdConnectClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\Service\Provider\Saml2ClientEntityWriter:
        decorates: Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter
        arguments:
            - '@Heptacom\AdminOpenAuth\Service\Provider\Saml2ClientEntityWriter.inner'

    Heptacom\AdminOpenAuth\OpenAuth\OneTimeTokenScopeRepository:
        decorates: Shopware\Core\Framework\Api\OAuth\ScopeRepository
        arguments:
            - '@Heptacom\AdminOpenAuth\OpenAuth\OneTimeTokenScopeRepository.inner'

    Heptacom\AdminOpenAuth\Subscriber\ApiAuthentication:
        arguments:
            - '@shopware.api.authorization_server'
            - '@Shopware\Core\Framework\Api\OAuth\UserRepository'
            - '@Shopware\Core\Framework\Api\OAuth\RefreshTokenRepository'

    Heptacom\AdminOpenAuth\Service\UserResolver:
        arguments:
            - '@user.repository'
            - '@language.repository'
