[PHP]
; Based on https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks.html#php-config-tweaks
; Some settings are not set since they don't make sense during development
zend.assertions=-1
opcache.interned_strings_buffer=20
zend.detect_unicode=0
realpath_cache_ttl=3600
